[package]
name = "propbot-indicators"
description = "Streaming technical indicator library"
version.workspace = true
edition.workspace = true

[dependencies]
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
